//
// This file is auto-generated by the script in .husky/patch-ugc-files.js
// Do not edit this file directly.
// If you need to make changes, edit the original file at: ./apps/ugc/src/lib/dayjs.ts
// The changes will be applied automatically as soon as you commit your changes.
//

import dayjs from "dayjs";
import advanced_format from "dayjs/plugin/advancedFormat";
import duration_plugin from "dayjs/plugin/duration";
import utc from "dayjs/plugin/utc";

dayjs.extend(utc);
dayjs.extend(duration_plugin);
dayjs.extend(advanced_format);

type Dayjs = dayjs.Dayjs;
export { dayjs, type Dayjs };

export type { Duration, DurationUnitsObjectType, DurationUnitType, CreateDurationType } from "dayjs/plugin/duration";