//
// This file is auto-generated by the script in .husky/patch-ugc-files.js
// Do not edit this file directly.
// If you need to make changes, edit the original file at: ./apps/ugc/src/lib/enum.ts
// The changes will be applied automatically as soon as you commit your changes.
//

import { z } from "zod";
import { Country, ReversedCountry } from "./countries";
import { Language, LanguageReversed } from "./languages";

/**
 * Defines the allowed types of rating systems.
 */
export const RatingType = z.enum([ "star", "heart", "thumbs", "smiley" ]);

/**
 * Defines the allowed types of styles for the showcase.
 */
export const ShowcaseStyle = z.enum([ "carousel", "grid", "list" ]);

/**
 * Define the type of the image
 */
export const ImageMimes = z.enum([
    "image/png",
    "image/jpeg",
    "image/pjpeg",
    "image/tiff",
    "image/webp",
    "image/gif",
    "image/svg+xml",
    "image/avif",
]);

/**
 * Define the allowed list of languages
 */
export const Locales = z.nativeEnum(Language);

/**
 * Define the allowed list of languages reversed
 * @type {ZodNativeEnum<LanguageReversed>}
 */
export const ReversedLocales = z.nativeEnum(LanguageReversed);

/**
 * Define the allowed list of device types
 */
export const DeviceType = z.enum([ "android", "ios", "windows", "macos", "linux", "other" ]);

/**
 * Define the allowed list of countries
 */
export const Countries = z.nativeEnum(Country);

/**
 * Define the allowed list of countries reversed
 */
export const ReversedCountries = z.nativeEnum(ReversedCountry);

/**
 * Define the allowed list of threshold scan frequencies
 */
export const ThresholdScanFrequency = z.enum([ "daily", "weekly", "monthly", "yearly" ]);

/**
 * Define the type of the week days
 */
export const Weekday = z.enum([ "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday" ]);

/**
 * Define the criteria for the QR code expiration
 */
export const ExpirationCriteria = z.enum([ "never", "time", "scan" ]);

/**
 * Define the criteria for renewing the QR code
 */
export const RenewCriteria = z.enum([ "never", "time", "manually" ]);

/**
 * Define the social media types
 */
export const Social = z.enum([
    "Facebook",
    "Twitter / X",
    "Instagram",
    "Linkedin",
    "Youtube",
    "Pinterest",
    "Tiktok",
    "Website",
    "WhatsApp",
    "Telegram",
    "Snapchat",
    "Twitch",
    "Spotify",
    "Soundcloud",
    "Vimeo",
    "Reddit",
    "Discord",
    "Github",
    "Tripadvisor",
    "Yelp",
    "Etsy",
    "Airbnb",
    "Booking",
]);

/**
 * The shape of the QR code dots
 */
export const QrShape = z.enum([ "circle", "diamond", "square" ]);

/**
 * The color type for the QR code
 */
export const QrColorType = z.enum([ "solid", "gradient" ]);

/**
 * Define the types of gradient
 */
export const GradientType = z.enum([ "linear", "radial" ]);